---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
script_dir:    "{{ playbook_dir }}/scripts"
binary_dir:    "{{ playbook_dir }}/resources/bin"

# default configuration for multiple host groups and roles
node_exporter_port: 9100
blackbox_exporter_port: 9115
kafka_exporter_port: 9308

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

# deployment methods, [binary, docker] docker deployment method is not recommended and deprecated.
deployment_method: binary
