---

- name: create common deploy directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ grafana_log_dir }}"
  - "{{ grafana_data_dir }}"

- name: push data source file
  template: src=data_source.json.j2 dest={{ grafana_data_dir }}/data_source.json mode=0644

- include_tasks: "{{ deployment_method }}_deployment.yml"

- name: prepare firewalld white list
  set_fact:
    firewalld_ports: "{{ [grafana_port ~ '/tcp'] + firewalld_ports }}"
