---

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- hosts: monitored_servers
  tags:
    - node_exporter
    - blackbox_exporter
  tasks:
    - name: stop node_exporter/blackbox_exporter by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      with_items:
        - node_exporter
        - blackbox_exporter
      when: process_supervision == 'supervise'

    - name: stop node_exporter/blackbox_exporter by systemd
      systemd: name={{ item }} state=stopped
      become: true
      when: process_supervision == 'systemd'
      with_items:
        - node_exporter-{{ node_exporter_port }}.service
        - blackbox_exporter-{{ blackbox_exporter_port }}.service

    - name: wait for node_exporter down
      wait_for: host={{ ansible_host }} port={{ node_exporter_port }} state=stopped

    - name: wait for blackbox_exporter down
      wait_for: host={{ ansible_host }} port={{ blackbox_exporter_port }} state=stopped


- hosts: alertmanager_servers
  tags:
    - alertmanager
  tasks:
    - name: stop alertmanager by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_alertmanager.sh
      when: process_supervision == 'supervise'

    - name: stop alertmanager by systemd
      systemd: name=alertmanager-{{ alertmanager_port }}.service state=stopped
      become: true
      when: process_supervision == 'systemd'

    - name: wait for alertmanager down
      wait_for: host={{ ansible_host }} port={{ alertmanager_port }} state=stopped


- hosts: monitoring_servers
  tags:
    - pushgateway
    - prometheus
  tasks:
    - name: stop monitoring modules by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      with_items:
        - pushgateway
        - prometheus
      when: process_supervision == 'supervise'

    - name: stop monitoring modules by systemd
      systemd: name={{ item }} state=stopped
      when: process_supervision == 'systemd'
      become: true
      with_items:
        - pushgateway-{{ pushgateway_port }}.service
        - prometheus-{{ prometheus_port }}.service

    - name: wait for pushgateway down
      wait_for: host={{ ansible_host }} port={{ pushgateway_port }} state=stopped

    - name: wait for prometheus down
      wait_for: host={{ ansible_host }} port={{ prometheus_port }} state=stopped

- hosts: grafana_servers
  tags:
    - grafana
  tasks:
    - name: stop grafana by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      when: process_supervision == 'supervise'
      with_items:
        - grafana

    - name: stop grafana by systemd
      systemd: name=grafana-{{ grafana_port }}.service state=stopped
      become: true
      when: process_supervision == 'systemd'

    - name: wait for grafana down
      wait_for: host={{ ansible_host }} port={{ grafana_port }} state=stopped

    - name: stop grafana_collector by supervise
      shell: cd {{ deploy_dir }}/scripts && ./stop_{{ item }}.sh
      when: process_supervision == 'supervise'
      with_items:
        - grafana_collector
