---
# tasks file for supervise

- name: create supervise status directory
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/status/{{ this_role_name }}"

- name: deploy supervise binary
  copy: src="{{ resources_dir }}/bin/{{ item }}" dest="{{ deploy_dir }}/bin/" mode=0755
  with_items:
  - supervise
  - svc
  - svstat

- name: create startup script - common start/stop
  template:
    src: "{{ item }}_role.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_{{ this_role_name }}.sh"
    mode: "0755"
  with_items:
    - start
    - stop
  vars:
    role_status_dir: status/{{ this_role_name }}
