---
# Common Tasks

- name: Ensure only one monitoring host exists
  fail: msg="One monitoring host should be specified."
  when: groups['monitoring_servers'] | length != 1

- name: Ensure monitored_servers exists
  fail: msg="monitored_servers should be specified."
  when: groups['monitored_servers'] | length < 1

- name: Ensure timezone variable is set
  fail: msg="Please set timezone variable in inventory.ini."
  when: (timezone is undefined) or (timezone is defined and timezone == "")

- name: Close old SSH control master processes
  raw: pkill -f "ssh.*ansible.*"
  ignore_errors: true
  changed_when: false
  failed_when: false
